name: Custom Clojure Fork Tests
run-name: Custom Clojure Fork Tests

on:
  workflow_dispatch:

jobs:
  gradle-test-custom-clojure:
    uses: ./.github/workflows/gradle-test.yml
    with:
      extra_gradle_flags: '-PdisableSmallMapsOptimisation'

  integration-test-custom-clojure:
    uses: ./.github/workflows/integration-test.yml
    with:
      extra_gradle_flags: '-PdisableSmallMapsOptimisation'

  property-test-custom-clojure:
    uses: ./.github/workflows/property-test.yml
    with:
      iteration_count: "100"
      simulation_iteration_count: "100"
      extra_gradle_flags: '-PdisableSmallMapsOptimisation'
